# Swasthik
# MITE

# Tutorial on Python Programming

In [1]:
import numpy as np
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [2]:
a = np.arange(3.0) 

a

array([0., 1., 2.])

In [4]:
import numpy as np

a = np.arange(2,7,1) 
a

array([2, 3, 4, 5, 6])

In [5]:
import numpy as np

a = np.arange(3,8,3) 
a

array([3, 6])

# Alternate method for Array Creation

In [6]:
import numpy as np
a = np.array([2,5,7,6])
a

array([2, 5, 7, 6])

In [7]:
import numpy as np
a = np.array([2,3,4,6])
print(a)

[2 3 4 6]


In [8]:
X2D = np.array([[11 ,12,13,11], [21, 22, 23, 24], [31,32,33,34]])

print('2D Numpy Array')
print(X2D)

2D Numpy Array
[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]


# IIlustarive Examples of ndarray.shape[]

In [10]:
# Example 1

#Get Dimensions of a 1D NumPy array using ndarray.shape
# Create a Numpy array from list of numbers
X1D = np.array([4, 5, 6, 7, 8, 9, 10, 11])

print('Shape of 1D numpy array : ', X1D.shape)
print('length of 1D numpy array : ', X1D.shape[0])


print(len(X1D))

Shape of 1D numpy array :  (8,)
length of 1D numpy array :  8
8


In [11]:
#Example 2

# Create a 2D Numpy array list of list
import numpy as np
X2D = np.array([[11 ,12,13,11], [21, 22, 23, 24], [31,32,33,34]])
print('2D Numpy Array')
print(X2D)
print("Shape of 2D Array")
print(X2D.shape)

2D Numpy Array
[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]
Shape of 2D Array
(3, 4)


In [12]:
#Get number of rows in this 2D NumPy array i.e.

numOfRows = X2D.shape[0]
print('Number of Rows : ', numOfRows)

Number of Rows :  3


In [13]:
#Get number of rows in this 2D NumPy array i.e.

numOfRows = np.size(X2D,0)
print('Number of Rows : ', numOfRows)

Number of Rows :  3


In [15]:
#Get total number of elements in this 2D NumPy array,
totalNumberofElements = X2D.shape[0] * X2D.shape[1]
print('Total Number of elements in 2D Numpy array : ',totalNumberofElements )

Total Number of elements in 2D Numpy array :  12


In [16]:
#Get total number of elements in this 2D NumPy array:

print('Total Number of elements in 2D Numpy array : ', np.size(X2D))

Total Number of elements in 2D Numpy array :  12


# Complete example

In [17]:
import numpy as np
a1 = np.arange(20) ##
print ("a1 = ",a1)
dim1=a1.ndim
shape1=a1.shape
size1=a1.itemsize
datatype1=a1.dtype.name
print ("Number of axes (dimensions) of the array = ", dim1)
print ("Dimension of the array = ", shape1)
print ("Total number of elements of the array = ", size1)
print ("Type of the elements in the array = ", datatype1)

a1 =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Number of axes (dimensions) of the array =  1
Dimension of the array =  (20,)
Total number of elements of the array =  4
Type of the elements in the array =  int32


# Function reshape()

The Convolution2D layers in Keras however, are designed to work with 3 dimensions per example.
They have 4-dimensional inputs and outputs. This covers colour images (nb_samples,
nb_channels, width, height), but more importantly, it covers deeper layers of the network, where
each example has become a set of feature maps i.e. (nb_samples, nb_features, width, height).

# Illustrative Examples of 2D array using reshape()

In [19]:
 a = np.arange(15) # 1D array

print(a)
print("Shape of 1D Array")
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Shape of 1D Array
(15,)


In [23]:
## reshape- it genearte matrix of 2 rows and 3 columns

c = a.reshape(3,5) # 2D array
print(c)
print("Shape of 2D Array")
print(c.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Shape of 2D Array
(3, 5)


In [24]:
## reshape- it genearte matrix of 2 rows and 3 columns

c = a.reshape(5,3) # 2D array
print(c)
print("Shape of 2D Array")
print(c.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Shape of 2D Array
(5, 3)


In [25]:
## reshape- it genearte matrix of 2 rows and 3 columns

c = a.reshape(15,1) # 2D array
print(c)
print("Shape of 2D Array")
print(c.shape)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]
Shape of 2D Array
(15, 1)


# Illustrative Examples of 3D Array using reshape()

In [26]:
#Example 1:

## reshape- it genearte 3D matrix
c = np.arange(24).reshape(2,3,4) # 3D array
print(c)
print('Axis 0 size : ', np.size(c, 0))
print('Axis 1 size : ', np.size(c, 1))
print('Axis 2 size : ', np.size(c, 2))
print("Shape of 3D Array")
print(c.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Axis 0 size :  2
Axis 1 size :  3
Axis 2 size :  4
Shape of 3D Array
(2, 3, 4)


In [27]:
# Example 2:

c = np.arange(27).reshape(3,3,3) # 3D array
print(c)
#Get number of elements per axis in 3D numpy array i.e.
print('Axis 0 size : ', np.size(c, 0))
print('Axis 1 size : ', np.size(c, 1))
print('Axis 2 size : ', np.size(c, 2))
print("Shape of 3D Array")
print(c.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Axis 0 size :  3
Axis 1 size :  3
Axis 2 size :  3
Shape of 3D Array
(3, 3, 3)


# Illustrative Examples of 4D Array using reshape()

In [30]:
# Example 4:

## reshape- it genearte matrix of 2 rows and 3 columns
c1 = np.arange(16).reshape(4,4) # 2D array
print(c1)
c = c1.reshape(2,2,2,2) # 4D array
print("Array after reshaping")
print(c)
print("Shape of Array after reshaping")
print(c.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Array after reshaping
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
Shape of Array after reshaping
(2, 2, 2, 2)


# If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [31]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [32]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


# ndarry.itemsize

In [33]:
#Example 1

# dtype of array is int8 (1 byte)
import numpy as np
x = np.array([2,4,6,8,10], dtype = np.int8)
print(x)
print(x.itemsize)

[ 2  4  6  8 10]
1


In [34]:
#Example 2

# dtype of array is int16 (2 bytes)
import numpy as np
x = np.array([2,4,6,8,10], dtype = np.int16)
print(x)
print(x.itemsize)

[ 2  4  6  8 10]
2


In [35]:
#Example 3

# dtype of array is float32 (8 bytes)
import numpy as np
x = np.array([2,4,6,8,10], dtype = np.float64)
print(x)
print(x.itemsize)

[ 2.  4.  6.  8. 10.]
8



# Get Dimensions of a 3D numpy array using numpy.size()

In [37]:
# Create a 3D Numpy array list of list of list

X3D = np.array([ [[11, 12, 13, 11], [21, 22, 23, 24], [31, 32, 33, 34]],

[[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]] ])

print(X3D)
#Get number of elements per axis in 3D numpy array i.e.
print('Axis 0 size : ', np.size(X3D, 0))
print('Axis 1 size : ', np.size(X3D, 1))
print('Axis 2 size : ', np.size(X3D, 2))

[[[11 12 13 11]
  [21 22 23 24]
  [31 32 33 34]]

 [[ 1  1  1  1]
  [ 2  2  2  2]
  [ 3  3  3  3]]]
Axis 0 size :  2
Axis 1 size :  3
Axis 2 size :  4


# Illustrative examples of Other Array Creation

In [38]:
import numpy as np

#b = np.array(([(1.5,2,3), (4,5,6)]),dtype=int)
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [39]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )

c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [40]:
np.arange( 0, 2, 0.3 ) # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [41]:
from numpy import pi

np.linspace( 0, 2, 9 ) # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [44]:
# x = np.linspace( 0, 2*pi, 100 ) # useful to evaluate function at lots of points
x = np.linspace( 0, 2*np.pi, 100 ) # useful to evaluate function at lots of points
f = np.sin(x)
print(x)
print(f)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

# Concatenating tensors in deep learning

In [47]:
a =np.array([[ 6, 1],
[2,0]])
b=np.array([[ 8, 3],
[6,7]])
print('a=',a)
print('b=',b)

a= [[6 1]
 [2 0]]
b= [[8 3]
 [6 7]]


In [48]:
np.vstack((a,b))

array([[6, 1],
       [2, 0],
       [8, 3],
       [6, 7]])

In [49]:
np.hstack((a,b))

array([[6, 1, 8, 3],
       [2, 0, 6, 7]])

# Splitting one array into several smaller ones

In [50]:
import numpy as np

b = np.arange(24).reshape(4,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [51]:
np.hsplit(b,3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])]

In [52]:
np.hsplit(b,(3,4))

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]),
 array([[ 3],
        [ 9],
        [15],
        [21]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])]

# Matrices Operation

# Array operation: Addition

In [57]:
import numpy as np
x1=np.arange(0,2)
#x1=np.arange(2)
print(x1)
x2=np.arange(2,4)
print(x2)
np.add(x1, x2)

[0 1]
[2 3]


array([2, 4])

In [58]:
a = np.matrix('1 2 3; 4 5 6; 7 8 9')

print(a)
b= np.matrix('10 20 30; 40 50 60; 70 80 90')
print(b)
np.add(a, b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


matrix([[11, 22, 33],
        [44, 55, 66],
        [77, 88, 99]])

# Matrix Addition using Nested Loop

In [59]:
# first matrix
a = [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
# second matrix
b = [[10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]]
# In this matrix we will store the sum of above matrices
# we have initialized all the elements of this matrix as zero
sum = [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]]
# iterating the matrix
# rows: number of nested lists in the main list
# columns: number of elements in the nested lists
for i in range(len(a)):
    for j in range(len(a[0])):
        sum[i][j] = a[i][j] + b[i][j]
        # displaying the output matrix
for num in sum:
    print(num)

[11, 22, 33]
[44, 55, 66]
[77, 88, 99]


# Matrix Addition using Nested List Comprehension

In [60]:
# first matrix
a = [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
# second matrix
b = [[10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]]
# In this matrix we will store the sum of above matrices
# we have initialized all the elements of this matrix as zero
sum = [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]]
# iterating the matrix
# rows: number of nested lists in the main list
# columns: number of elements in the nested lists
result = [[a[i][j] + b[i][j] for j in range(len(a[0]))] for i in range(len(a))]
for r in result:
    print(r)

[11, 22, 33]
[44, 55, 66]
[77, 88, 99]


# Array operation: Subtraction

In [61]:
a = np.matrix('1 2 3; 4 5 6; 7 8 9')

print(a)
b= np.matrix('10 20 30; 40 50 60; 70 80 90')
print(b)
np.subtract(b, a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


matrix([[ 9, 18, 27],
        [36, 45, 54],
        [63, 72, 81]])

In [62]:
# This program is to subtrac two given matrices

# We are using the concept of nested lists to represent matrix
# first matrix
a = [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
# second matrix
b = [[10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]]
# In this matrix we will store the sum of above matrices
# we have initialized all the elements of this matrix as zero
sub = [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]
# iterating the matrix
# rows: number of nested lists in the main list
# columns: number of elements in the nested lists
for i in range(len(a)):
    for j in range(len(a[0])):
        sub[i][j] = b[i][j] - a[i][j]
        # displaying the output matrix
for num in sub:
    print(num)

[9, 18, 27]
[36, 45, 54]
[63, 72, 81]


# Array operation: Multiplication

In [63]:
import numpy as np

a = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(a)
b= np.matrix('10 20 30; 40 50 60; 70 80 90')
print (b)
np.matmul(a, b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


matrix([[ 300,  360,  420],
        [ 660,  810,  960],
        [1020, 1260, 1500]])

# Matrix Multiplication using Nested Loop

In [65]:
# first matrix
A = [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
# second matrix
B = [[10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]]
# result is 3x4
mul_result = [[0,0,0],
              [0,0,0],
              [0,0,0]]
    
# iterate through rows of X
for i in range(len(A)):
    # iterate through columns of A
    for j in range(len(B[0])):
        # iterate through rows of B
        for k in range(len(B)):
            mul_result[i][j] += A[i][k] * B[k][j]

for r in mul_result:
    print(r)

[300, 360, 420]
[660, 810, 960]
[1020, 1260, 1500]


# Matrix Multiplication Using Nested List Comprehension

In [66]:
# Illustration of zip inbulit function

x = [1, 2, 3]
y = [4, 5, 6]
zipped = zip(x, y)
list(zipped)

[(1, 4), (2, 5), (3, 6)]

# Matrix Power

In [72]:
import numpy as np
import matplotlib.pyplot as pyplot
X = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(X)
np.power(X, 2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


matrix([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]], dtype=int32)

# Array operation: Division

In [73]:
a = np.matrix('2 4 6; 4 8 6; 2 8 10')

print(a)
b= 2
print(b)
np.divide(a, b)

[[ 2  4  6]
 [ 4  8  6]
 [ 2  8 10]]
2


matrix([[1., 2., 3.],
        [2., 4., 3.],
        [1., 4., 5.]])

# Matrix Inverse

In [74]:
import numpy as np

import matplotlib.pyplot as pyplot
a = np.matrix('1 2 3; 4 5 6; 7 8 0')
print(a)
ainv = np.linalg.inv(a)
print (ainv)

[[1 2 3]
 [4 5 6]
 [7 8 0]]
[[-1.77777778  0.88888889 -0.11111111]
 [ 1.55555556 -0.77777778  0.22222222]
 [-0.11111111  0.22222222 -0.11111111]]
